# apiVersion: dapr.io/v1alpha1
# kind: Component
# metadata:
#   name: order_pub_sub
# spec:
#   type: pubsub.rabbitmq
#   version: v1
#   metadata:
#   - name: host
#     value: "amqp://admin:password@localhost:5672"
#   - name: durable
#     value: "false"
#   - name: deletedWhenUnused
#     value: "false"
#   - name: autoAck
#     value: "false"
#   - name: reconnectWait
#     value: "0"
#   - name: concurrency
#     value: parallel
apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: order_pub_sub
spec:
  type: pubsub.redis
  version: v1
  metadata:
  - name: redisHost
    value: localhost:6379
  - name: redisPassword
    value: ""

